10 REM ON THE DISK. WOULD YOU LIKE TO CONTINUE.
20 PRINT "WORKING"
30 PRINT "WOULD YOU LIKE TO CONTINUE";
40 A$ = INKEY$
50 IF A$ = "" THEN GOTO 40
60 IF A$ = "Y" OR A$ = "y" THEN GOTO 20
70 IF A$ = "N" OR A$ = "n" OR A$ = "D" OR A$ = "d" THEN CHAIN "MENU.BAS"
80 GOTO 40
